services:
  seclink:
    build: .
    command:
      - "-v"
      - "-1"
      - "serve"
    ports:
      - '3000:3000' # Web port
      - '9000:9000' # Admin port
    networks:
      - seclink

networks:
  seclink:
