// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Link struct {
	ID       string
	Expires  int64
	PostName string
}

type Post struct {
	Name string
	Path string
}
