// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :exec
INSERT INTO links (id, expires, post_name)
VALUES (?, ?, ?)
`

type CreateLinkParams struct {
	ID       string
	Expires  int64
	PostName string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink, arg.ID, arg.Expires, arg.PostName)
	return err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (name, path)
VALUES (?, ?)
`

type CreatePostParams struct {
	Name string
	Path string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost, arg.Name, arg.Path)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE name = ?
`

func (q *Queries) DeletePost(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePost, name)
	return err
}

const getAllLinks = `-- name: GetAllLinks :many
SELECT id, expires, post_name FROM links
ORDER BY id
`

func (q *Queries) GetAllLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.Expires, &i.PostName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
