// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :exec
INSERT INTO links (id, expires, post_name)
VALUES (?, ?, ?)
`

type CreateLinkParams struct {
	ID       string
	Expires  int64
	PostName string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink, arg.ID, arg.Expires, arg.PostName)
	return err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (name, path)
VALUES (?, ?)
`

type CreatePostParams struct {
	Name string
	Path string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost, arg.Name, arg.Path)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE name = ?
`

func (q *Queries) DeletePost(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePost, name)
	return err
}

const getAllLinks = `-- name: GetAllLinks :many
SELECT posts.name, posts.path, links.id, links.expires, links.post_name
FROM links
JOIN posts ON links.post_name = posts.name
`

type GetAllLinksRow struct {
	Post Post
	Link Link
}

func (q *Queries) GetAllLinks(ctx context.Context) ([]GetAllLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLinksRow
	for rows.Next() {
		var i GetAllLinksRow
		if err := rows.Scan(
			&i.Post.Name,
			&i.Post.Path,
			&i.Link.ID,
			&i.Link.Expires,
			&i.Link.PostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT name, path FROM posts
`

func (q *Queries) GetAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(&i.Name, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLink = `-- name: GetLink :one
SELECT links.id, links.expires, links.post_name, posts.name, posts.path
FROM links
JOIN posts ON links.post_name = posts.name
WHERE links.id = ?
`

type GetLinkRow struct {
	Link Link
	Post Post
}

func (q *Queries) GetLink(ctx context.Context, id string) (GetLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i GetLinkRow
	err := row.Scan(
		&i.Link.ID,
		&i.Link.Expires,
		&i.Link.PostName,
		&i.Post.Name,
		&i.Post.Path,
	)
	return i, err
}
